"""initial_storage"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "7ea697a3bc8d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_key", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("since", sa.DateTime(timezone=True), nullable=False),
        sa.Column("until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_key"),
    )
    op.create_table(
        "papers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_id", sa.String(), nullable=False),
        sa.Column("doi", sa.String(), nullable=True),
        sa.Column("arxiv_id", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("normalized_title", sa.String(), nullable=False),
        sa.Column("abstract", sa.String(), nullable=True),
        sa.Column("authors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paper_url", sa.String(), nullable=False),
        sa.Column("pdf_url", sa.String(), nullable=True),
        sa.Column("venue", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("arxiv_id"),
        sa.UniqueConstraint("canonical_id"),
        sa.UniqueConstraint("doi"),
    )
    op.create_index(
        op.f("ix_papers_normalized_title"), "papers", ["normalized_title"], unique=False
    )
    op.create_index(op.f("ix_papers_published_at"), "papers", ["published_at"], unique=False)
    op.create_table(
        "topics",
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("parent", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("slug"),
    )
    op.create_table(
        "paper_metrics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("paper_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("paper_id", "source", "name", "observed_at"),
    )
    op.create_index(op.f("ix_paper_metrics_paper_id"), "paper_metrics", ["paper_id"], unique=False)
    op.create_table(
        "paper_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("paper_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_id"),
    )
    op.create_index(op.f("ix_paper_sources_paper_id"), "paper_sources", ["paper_id"], unique=False)
    op.create_table(
        "paper_summaries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("paper_id", sa.Uuid(), nullable=False),
        sa.Column("generation_key", sa.String(), nullable=False),
        sa.Column("input_hash", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("prompt_version", sa.String(), nullable=False),
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_texts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("generation_key"),
    )
    op.create_index(
        op.f("ix_paper_summaries_paper_id"), "paper_summaries", ["paper_id"], unique=False
    )
    op.create_table(
        "paper_topics",
        sa.Column("paper_id", sa.Uuid(), nullable=False),
        sa.Column("topic_slug", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["papers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topic_slug"],
            ["topics.slug"],
        ),
        sa.PrimaryKeyConstraint("paper_id", "topic_slug"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("paper_topics")
    op.drop_index(op.f("ix_paper_summaries_paper_id"), table_name="paper_summaries")
    op.drop_table("paper_summaries")
    op.drop_index(op.f("ix_paper_sources_paper_id"), table_name="paper_sources")
    op.drop_table("paper_sources")
    op.drop_index(op.f("ix_paper_metrics_paper_id"), table_name="paper_metrics")
    op.drop_table("paper_metrics")
    op.drop_table("topics")
    op.drop_index(op.f("ix_papers_published_at"), table_name="papers")
    op.drop_index(op.f("ix_papers_normalized_title"), table_name="papers")
    op.drop_table("papers")
    op.drop_table("ingestion_runs")
    # ### end Alembic commands ###
