import { act, fireEvent, render, screen } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { JobPanel } from '../src/JobPanel'
import { job } from './fixtures'

beforeEach(() => vi.useFakeTimers())
afterEach(() => { vi.useRealTimers(); vi.unstubAllGlobals() })

describe('durable analysis jobs', () => {
  it('submits once, polls to completion, and stops', async () => {
    const fetch = vi.fn().mockResolvedValueOnce(Response.json(job))
      .mockResolvedValueOnce(Response.json({ ...job, status: 'running' }))
      .mockResolvedValueOnce(Response.json({ ...job, status: 'succeeded' }))
    vi.stubGlobal('fetch', fetch)
    const complete = vi.fn()
    render(<JobPanel paperId={job.paper_id} initialJob={null} hasSummary={false} onComplete={complete} />)
    const button = screen.getByRole('button', { name: '生成分析' })
    await act(async () => { fireEvent.click(button); fireEvent.click(button) })
    expect(fetch).toHaveBeenCalledTimes(1)
    expect(screen.getByText('等待处理')).toBeVisible()
    await act(() => vi.advanceTimersByTimeAsync(1000))
    expect(screen.getByText('正在生成分析')).toBeVisible()
    await act(() => vi.advanceTimersByTimeAsync(2500))
    expect(complete).toHaveBeenCalledTimes(1)
    await act(() => vi.advanceTimersByTimeAsync(10_000))
    expect(fetch).toHaveBeenCalledTimes(3)
  })
  it('resumes a stored queued job and recovers polling without posting another task', async () => {
    const fetch = vi.fn().mockRejectedValueOnce(new TypeError('network'))
      .mockResolvedValueOnce(Response.json({ ...job, status: 'skipped' }))
    vi.stubGlobal('fetch', fetch)
    const complete = vi.fn()
    render(<JobPanel paperId={job.paper_id} initialJob={job} hasSummary={false} onComplete={complete} />)
    await act(() => vi.advanceTimersByTimeAsync(1000))
    expect(screen.getByRole('alert')).toHaveTextContent('任务可能仍在后台运行')
    fireEvent.click(screen.getByRole('button', { name: '恢复状态更新' }))
    await act(() => vi.advanceTimersByTimeAsync(1000))
    expect(screen.getByText('本次分析已跳过')).toBeVisible()
    expect(complete).toHaveBeenCalledOnce()
    expect(fetch.mock.calls.every(call => !call[1]?.method)).toBe(true)
  })
  it('accepts a token after 401 and sends it only in the request header', async () => {
    const fetch = vi.fn().mockResolvedValueOnce(new Response('', { status: 401 }))
      .mockResolvedValueOnce(Response.json(job))
    vi.stubGlobal('fetch', fetch)
    render(<JobPanel paperId={job.paper_id} initialJob={{ ...job, status: 'failed' }} hasSummary={false} onComplete={vi.fn()} />)
    await act(async () => fireEvent.click(screen.getByRole('button', { name: '重试分析' })))
    expect(screen.getByRole('alert')).toHaveTextContent('有效的访问令牌')
    fireEvent.change(screen.getByLabelText('访问令牌'), { target: { value: 'fixture-token' } })
    await act(async () => fireEvent.click(screen.getByRole('button', { name: '重试分析' })))
    expect(fetch.mock.calls[1][1].headers).toEqual({ Authorization: 'Bearer fixture-token' })
    expect(localStorage.length).toBe(0)
    expect(sessionStorage.length).toBe(0)
  })
  it('aborts polling when leaving the page', async () => {
    const fetch = vi.fn().mockResolvedValue(Response.json({ ...job, status: 'running' }))
    vi.stubGlobal('fetch', fetch)
    const { unmount } = render(<JobPanel paperId={job.paper_id} initialJob={job} hasSummary={false} onComplete={vi.fn()} />)
    await act(() => vi.advanceTimersByTimeAsync(1000))
    unmount()
    await act(() => vi.advanceTimersByTimeAsync(10_000))
    expect(fetch).toHaveBeenCalledTimes(1)
    expect(fetch.mock.calls[0][1].signal.aborted).toBe(true)
  })
})
