/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Feed
         * @description Publication window [since, until), default last 7 days; stable score ordering.
         */
        get: operations["feed_api_v1_feed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/papers/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detail
         * @description Metadata, metrics, original source records and evidence-grounded analysis.
         */
        get: operations["detail_api_v1_papers__paper_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/papers/{paper_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Summarize
         * @description Queue a durable, idempotent analysis job. Poll GET /jobs/{id}; run a worker.
         */
        post: operations["summarize_api_v1_papers__paper_id__summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job */
        get: operations["job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Topics */
        get: operations["topics_api_v1_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Topic Detail */
        get: operations["topic_detail_api_v1_topics__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{slug}/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Topic Papers */
        get: operations["topic_papers_api_v1_topics__slug__papers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Process liveness; does not mutate or migrate the database.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Evidence */
        Evidence: {
            /** Field */
            field: string;
            /**
             * Paper Id
             * Format: uuid
             */
            paper_id: string;
            /** Chunk Id */
            chunk_id: string;
            /** Quote */
            quote: string;
        };
        /** Feed */
        Feed: {
            /** Items */
            items: components["schemas"]["FeedItem"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /**
             * Since
             * Format: date-time
             */
            since: string;
            /**
             * Until
             * Format: date-time
             */
            until: string;
        };
        /** FeedItem */
        FeedItem: {
            paper: components["schemas"]["PaperView"];
            /** Score */
            score: number | null;
            explanation: components["schemas"]["Score"];
            /** Topics */
            topics: string[];
            /** Metrics */
            metrics: {
                [key: string]: number | null;
            };
            summary: components["schemas"]["SummaryPreview"] | null;
        };
        /** GenerationView */
        GenerationView: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Prompt Version */
            prompt_version: string;
            /** Input Hash */
            input_hash: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "abstract-only" | "full-text";
            /** Source Texts */
            source_texts: components["schemas"]["SourceText"][];
            usage: components["schemas"]["Usage"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Comparison Sources */
            comparison_sources: components["schemas"]["SourceText"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobView */
        JobView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Paper Id
             * Format: uuid
             */
            paper_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "skipped" | "failed";
            /** Error */
            error: string | null;
            /** Attempts */
            attempts: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MetricView */
        MetricView: {
            /** Name */
            name: string;
            /** Source */
            source: string;
            /** Value */
            value: number | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
        /** PaperComparison */
        PaperComparison: {
            /** Prior State */
            prior_state: string;
            /** Current Change */
            current_change: string;
            /** Major Difference */
            major_difference: string;
            /** Inherited Ideas */
            inherited_ideas: string[];
            /** New Ideas */
            new_ideas: string[];
            /** Tradeoffs */
            tradeoffs: string[];
            /** Importance */
            importance: number;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
        };
        /** PaperDetail */
        PaperDetail: {
            paper: components["schemas"]["PaperView"];
            /** Topics */
            topics: string[];
            /** Metrics */
            metrics: components["schemas"]["MetricView"][];
            /** Sources */
            sources: components["schemas"]["SourceView"][];
            summary: components["schemas"]["PaperSummary"] | null;
            comparison: components["schemas"]["PaperComparison"] | null;
            /**
             * Comparison Status
             * @enum {string}
             */
            comparison_status: "ready" | "not-generated" | "insufficient-prior-papers";
            generation: components["schemas"]["GenerationView"] | null;
            job: components["schemas"]["JobView"] | null;
        };
        /** PaperSummary */
        PaperSummary: {
            /** One Sentence */
            one_sentence: string;
            /** Problem */
            problem: string | null;
            /** Why Problem Matters */
            why_problem_matters: string | null;
            /** Previous Approaches */
            previous_approaches: string[];
            /** Previous Limitations */
            previous_limitations: string[];
            /** Method */
            method: string | null;
            /** Key Innovations */
            key_innovations: string[];
            /** Experiment Setup */
            experiment_setup: string | null;
            /** Key Results */
            key_results: string[];
            /** Limitations */
            limitations: string[];
            /** Why It Matters */
            why_it_matters: string | null;
            /** Engineering Takeaways */
            engineering_takeaways: string[];
            /** What Changed */
            what_changed: string | null;
            /** Confidence */
            confidence: number;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
        };
        /** PaperView */
        PaperView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Canonical Id */
            canonical_id: string;
            /** Doi */
            doi: string | null;
            /** Arxiv Id */
            arxiv_id: string | null;
            /** Title */
            title: string;
            /** Abstract */
            abstract: string | null;
            /** Authors */
            authors: string[];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Paper Url */
            paper_url: string;
            /** Pdf Url */
            pdf_url: string | null;
            /** Venue */
            venue: string | null;
        };
        /** Score */
        Score: {
            /** Value */
            value: number | null;
            /** Signals */
            signals: {
                [key: string]: number | null;
            };
            /** Available Weights */
            available_weights: {
                [key: string]: number;
            };
        };
        /** SourceText */
        SourceText: {
            /**
             * Paper Id
             * Format: uuid
             */
            paper_id: string;
            /** Title */
            title: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /**
             * Scope
             * @enum {string}
             */
            scope: "abstract-only" | "full-text";
            /** Chunks */
            chunks: components["schemas"]["TextChunk"][];
        };
        /** SourceView */
        SourceView: {
            /** Source */
            source: string;
            /** Source Id */
            source_id: string;
            /** Raw */
            raw: {
                [key: string]: unknown;
            };
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
        };
        /** SummaryPreview */
        SummaryPreview: {
            /** One Sentence */
            one_sentence: string;
            /** What Changed */
            what_changed: string | null;
            /**
             * Scope
             * @enum {string}
             */
            scope: "abstract-only" | "full-text";
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** TextChunk */
        TextChunk: {
            /** Id */
            id: string;
            /** Section */
            section: string;
            /** Page */
            page: number | null;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Text */
            text: string;
        };
        /** TopicView */
        TopicView: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Parent */
            parent: string | null;
        };
        /** Usage */
        Usage: {
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Cost Usd */
            cost_usd?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    feed_api_v1_feed_get: {
        parameters: {
            query?: {
                type?: "new" | "hot";
                topic?: string | null;
                since?: string | null;
                until?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feed"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_api_v1_papers__paper_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summarize_api_v1_papers__paper_id__summary_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    topics_api_v1_topics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicView"][];
                };
            };
        };
    };
    topic_detail_api_v1_topics__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    topic_papers_api_v1_topics__slug__papers_get: {
        parameters: {
            query?: {
                type?: "new" | "hot";
                since?: string | null;
                until?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feed"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
